name: Build & Push Backend

on:
  push:
    paths:
      - 'components/backend/**'
      - 'components/python/**'
      - '.github/workflows/build-backend.yml'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build \
            --target prod \
            -t ghcr.io/${{ github.repository_owner }}/roter-kompass-backend:latest \
            -f components/python/Dockerfile \
            . # Wichtig: Kontext ist das Root-Verzeichnis!

          docker push ghcr.io/${{ github.repository_owner }}/roter-kompass-backend:latest
